#!/usr/bin/env bash
echo "$PWD"
if [ -f "/usr/bin/mokka" ]; then
echo "Symlink exists"
fi
ORIGINFILE=$(readlink -f /usr/bin/mokka)
ORIGINDIR=${ORIGINFILE%/*}/
cd "$ORIGINDIR"

if command -v python3.12 &> /dev/null
then
    python3.12 mokkas "$@"
else
    python mokkas "$@"
fi
