#!/usr/bin/env bash

if [[ "$0" == "/usr/bin/mokka" ]]; then
    ORIGINFILE=$(readlink -f /usr/bin/mokka)
    ORIGINDIR=${ORIGINFILE%/*}/
    cd "$ORIGINDIR"
else
    cd ~/mokka
fi

if command -v python3.12 &> /dev/null
then
    python3.12 mokkas "$@"
else
    python mokkas "$@"
fi
