[MARKET]
title = "MOKKA Official"
author = "Till Vennefrohne"

[[MODULES]]
title = "Testmodule"
ident = "test"
description = "This is a test module"
path = "/home/pi/mokka/examples/asd"

[[MODULES]]
title = "MOKKA Webinterface"
ident = "mweb"
description = "Webinterface for MOKKA"
path = "~/mokka/examples/mweb"


